
export const GET_DATA_BEGIN   = 'GET_DATA_BEGIN';

export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS'


